/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.example.demo.models;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqX92+Deuc+LA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqX92+Deuc+LA= >>
// ----------- >>
public class Player1 {
  // ----------- << method.annotations@AAAAAAFqX934oOwC67k= >>
  // ----------- >>
  public void markX() {
  // ----------- << method.body@AAAAAAFqX934oOwC67k= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFqX92+Deuc+LA= >>
// ----------- >>
}