/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package rebel;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqX944KOxXjoc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqX944KOxXjoc= >>
// ----------- >>
public class Player2 {
  // ----------- << method.annotations@AAAAAAFqX95et+y9LnY= >>
  // ----------- >>
  public void markO() {
  // ----------- << method.body@AAAAAAFqX95et+y9LnY= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFqX944KOxXjoc= >>
// ----------- >>
}