/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package rebel;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqEL341BmtoDw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqEL341BmtoDw= >>
// ----------- >>
public class Rubic {
  // ----------- << attribute.annotations@AAAAAAFqEMiOCh2cTeM= >>
  // ----------- >>
  private enum mark;

  // ----------- << attribute.annotations@AAAAAAFqEN6vjB8uvmI= >>
  // ----------- >>
  private boolean empty;

  // ----------- << attribute.annotations@AAAAAAFqEL62BRnYpyE= >>
  // ----------- >>
  private Board board;

  // ----------- << attribute.annotations@AAAAAAFqWXWqIXIrOUc= >>
  // ----------- >>
  private Board ;

  // ----------- << attribute.annotations@AAAAAAFqX9ydX+kdqvQ= >>
  // ----------- >>
  private Board board;

  public enum getMark() {
    return mark;
  }

  public boolean isEmpty() {
    return empty;
  }

  public Board getBoard() {
    return board;
  }

  public Board get() {
    return ;
  }

  public Board getBoard() {
    return board;
  }

  public void setMark(enum mark) {
    this.mark = mark;
  }

  public void setEmpty(boolean empty) {
    this.empty = empty;
  }

  public void setBoard(Board board) {
    this.board = board;
  }

  public void set(Board ) {
    this. = ;
  }

  public void setBoard(Board board) {
    this.board = board;
  }

  public void linkBoard(Board _board) {
    if (_board != null) {
      _board.getRubic().add(this);
    }

    unlinkBoard();
    setBoard(_board);
  }

  public void link(Board _) {
    if (_ != null) {
      _.unlink();
      _.set(this);
    }

    unlink();
    set(_);
  }

  public void linkBoard(Board _board) {
    if (_board != null) {
      _board.getRubic().add(this);
    }

    unlinkBoard();
    setBoard(_board);
  }

  public void unlinkBoard() {
    if (getBoard() != null) {
      getBoard().getRubic().remove(this);
      setBoard(null);
    }
  }

  public void unlink() {
    if (get() != null) {
      get().set(null);
      set(null);
    }
  }

  public void unlinkBoard() {
    if (getBoard() != null) {
      getBoard().getRubic().remove(this);
      setBoard(null);
    }
  }

  // ----------- << method.annotations@AAAAAAFqEON2gSBBuu4= >>
  // ----------- >>
  public void setPlayerMark() {
  // ----------- << method.body@AAAAAAFqEON2gSBBuu4= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqEOTl0yIFsNM= >>
  // ----------- >>
  public void setIsEmpty() {
  // ----------- << method.body@AAAAAAFqEOTl0yIFsNM= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqWWLGS2OAU5A= >>
  // ----------- >>
  public void IsEmpty() {
  // ----------- << method.body@AAAAAAFqWWLGS2OAU5A= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFqEL341BmtoDw= >>
// ----------- >>
}