/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package RootPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>
public class Board {
  // ----------- << attribute.annotations@AAAAAAFqEbOtPr4u4qs= >>
  // ----------- >>
  private Rubic rubices[3,3];
  private boolean currectPlayer = true;

  public Board(){

    init();
  }

  public init()
  {
    for(int i = 0 ; i<3;i++)
    {
      for(int j =0; j<3;j++)
      {
        rubices[i,j] = new Rubic();
        
      }
    }
  }

  public GetRubices()
  {
    return this.rubices;
  }
  public GetCurrectPlayer()
  {
    return this.currectPlayer;
  }
  // ----------- << method.annotations@AAAAAAFqEXy+QBhCKio= >>
  // ----------- >>
  public void registersMove(int row,int col,enum mark) {
  // ----------- << method.body@AAAAAAFqEXy+QBhCKio= >>
  // ----------- >>

      this.rubices[row,col].setMark(mark);
  }
  // ----------- << method.annotations@AAAAAAFqEYHjVxiQ3rk= >>
  // ----------- >>
  public void SwapPlayers() {
  // ----------- << method.body@AAAAAAFqEYHjVxiQ3rk= >>
  // ----------- >>
      this.currectPlayer = !this.currectPlayer;
  }
// ----------- << class.extras@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>
}