/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package rebel;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqEL341BmtoDw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqEL341BmtoDw= >>
// ----------- >>
public class Rubic {
  // ----------- << attribute.annotations@AAAAAAFqEMiOCh2cTeM= >>
  // ----------- >>
  private enum mark;
  private boolean empty;
  private Board board;

  public enum getMark() {
    return mark;
  }

  public Rubic(Board board)
  {
    this.board = board;
  }

  public boolean isEmpty() {
    return empty;
  }
 
  public Board getBoard() {
    return board;
  }

  public void setMark(enum mark) {
    this.mark = mark;
  }

  public void setEmpty(boolean empty) {
    this.empty = empty;
  }

 
  public void setBoard(Board board) {
    this.board = board;
  }
  // ----------- << method.annotations@AAAAAAFqEON2gSBBuu4= >>
  // ----------- >>
  public void setPlayerMark() {
  // ----------- << method.body@AAAAAAFqEON2gSBBuu4= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqEOTl0yIFsNM= >>
  // ----------- >>
  public void setIsEmpty() {
  // ----------- << method.body@AAAAAAFqEOTl0yIFsNM= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqWWLGS2OAU5A= >>
  // ----------- >>
  public void IsEmpty() {
  // ----------- << method.body@AAAAAAFqWWLGS2OAU5A= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFqEL341BmtoDw= >>
// ----------- >>
}