/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package TechMaven.TechMaven.entities;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>
public class Board {
  // ----------- << attribute.annotations@AAAAAAFqEbOtPr4u4qs= >>
  // ----------- >>
  private Rubic [][] rubices = new Rubic[3][3];
  
  private boolean currectPlayer = true;

  public Board(){

    init();
  }

  public void init()
  {
    for(int i = 0 ; i<3;i++)
    {
      for(int j =0; j<3;j++)
      {
        rubices[i][j] = new Rubic(this);
        
      }
    }
  }

  public Rubic[][] GetRubices()
  {
    return this.rubices;
  }
  public Boolean GetCurrectPlayer()
  {
    return this.currectPlayer;
  }
  // ----------- << method.annotations@AAAAAAFqEXy+QBhCKio= >>
  // ----------- >>
  public void registersMove(int row,int col,char mark) {
  // ----------- << method.body@AAAAAAFqEXy+QBhCKio= >>
  // ----------- >>
      this.rubices[row][col].setMark(mark);
  }
  // ----------- << method.annotations@AAAAAAFqEYHjVxiQ3rk= >>
  // ----------- >>
  public void SwapPlayers() {
  // ----------- << method.body@AAAAAAFqEYHjVxiQ3rk= >>
  // ----------- >>
      this.currectPlayer = !this.currectPlayer;
  }
// ----------- << class.extras@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>

public void printBoard() {
	// TODO Auto-generated method stub
		
	for(int i = 0 ; i<3;i++)
    {
      for(int j =0; j<3;j++)
      {
       
        System.out.print(rubices[i][j]);
        
      }
      	System.out.println("-----------");
    }
	
}
}