/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package TechMaven.TechMaven.entities;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqEL+umRp+/yI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqEL+umRp+/yI= >>
// ----------- >>
public class Player {
  // ----------- << attribute.annotations@AAAAAAFqEN3vMB6cSgU= >>
  // ----------- >>
  private int  wins;

  // ----------- << attribute.annotations@AAAAAAFqEOsueyfBRe4= >>
  // ----------- >>
  private char mark;
  
  public Player(char mark)
  {
	  setMark(mark);
	  setWins(0);
  }
  
// ----------- << class.extras@AAAAAAFqEL+umRp+/yI= >>
// ----------- >>


public int getWins() {
	return wins;
}


public void setWins(int wins) {
	this.wins = wins;
}


public char getMark() {
	return mark;
}


public void setMark(char mark) {
	this.mark = mark;
}
}