/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package TechMaven.TechMaven.entities;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqEL341BmtoDw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqEL341BmtoDw= >>
// ----------- >>
public class Rubic {
  // ----------- << attribute.annotations@AAAAAAFqEMiOCh2cTeM= >>
  // ----------- >>
  private char mark;
  private boolean empty;
  private Board board;

 
  public char getMark() {
    return mark;
  }

  public Rubic(Board board)
  {
	this.mark = ' ';
    this.board = board;
  }

  public boolean isEmpty() {
    return empty;
  }
 
  public Board getBoard() {
    return board;
  }

  public void setMark(char mark) {
    this.mark = mark;
  }

  public void setEmpty(boolean empty) {
    this.empty = empty;
  }

 
  public void setBoard(Board board) {
    this.board = board;
  }
  
  // ----------- << method.annotations@AAAAAAFqWWLGS2OAU5A= >>
  // ----------- >>
  public boolean IsEmpty() {
  // ----------- << method.body@AAAAAAFqWWLGS2OAU5A= >>
  // ----------- >>
	  return this.mark == ' ' ? true : false;
  }
  
  @Override
	public String toString() {
		// TODO Auto-generated method stub
		return " |" + mark +"| ";
	}
// ----------- << class.extras@AAAAAAFqEL341BmtoDw= >>
// ----------- >>
}