/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.example.demo.boundries;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFp/KtV9nBZOaw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp/KtV9nBZOaw= >>
// ----------- >>
public class AnnouncesMessage {
  // ----------- << method.annotations@AAAAAAFqX8QAfBy22Jc= >>
  // ----------- >>
  public void show() {
  // ----------- << method.body@AAAAAAFqX8QAfBy22Jc= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFp/KtV9nBZOaw= >>
// ----------- >>
}