/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package RootPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFpV1uqFmgq5+0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFpV1uqFmgq5+0= >>
// ----------- >>
public class ShowBoard {
  // ----------- << method.annotations@AAAAAAFqEXQmdBefqFE= >>
  // ----------- >>
  public void SelectMove() {
  // ----------- << method.body@AAAAAAFqEXQmdBefqFE= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqEZBDWhl6wRE= >>
  // ----------- >>
  public ShowBoard(Board board) {
  // ----------- << method.body@AAAAAAFqEZBDWhl6wRE= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFpV1uqFmgq5+0= >>
// ----------- >>
}