/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package RootPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFp/Kvq2XBejTo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp/Kvq2XBejTo= >>
// ----------- >>
public class PlayGameController {
  // ----------- << method.annotations@AAAAAAFqEXYlzBfXDrg= >>
  // ----------- >>

  private Board board;
  private Player1 player1,Player2 player2;
  
  public void IsAvilableMove() {
  // ----------- << method.body@AAAAAAFqEXYlzBfXDrg= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqX8As9hxl4EM= >>
  // ----------- >>
  public void CheckWin() {
  // ----------- << method.body@AAAAAAFqX8As9hxl4EM= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqX8DLTBxxdcg= >>
  // ----------- >>
  public void AddMoveToBoard() {
  // ----------- << method.body@AAAAAAFqX8DLTBxxdcg= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqX8HF6hx4wg4= >>
  // ----------- >>
  public void RestartGame() {
  // ----------- << method.body@AAAAAAFqX8HF6hx4wg4= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqX8LzjhyoV7g= >>
  // ----------- >>
  public void ShowMessage() {
  // ----------- << method.body@AAAAAAFqX8LzjhyoV7g= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFp/Kvq2XBejTo= >>
// ----------- >>
}