/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package TechMaven.TechMaven.controller;

import java.util.*;

import TechMaven.TechMaven.entities.Board;
import TechMaven.TechMaven.entities.Player;
import TechMaven.TechMaven.entities.Rubic;

import java.time.*;



// ----------- << imports@AAAAAAFp/Kvq2XBejTo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp/Kvq2XBejTo= >>
// ----------- >>
public class PlayGameController {
  // ----------- << method.annotations@AAAAAAFqEXYlzBfXDrg= >>
  // ----------- >>

  private Board board;
  private Player player1,player2;
  private boolean currectPlayer = true;

  public Boolean IsAvilableMove(int postions) {
  // ----------- << method.body@AAAAAAFqEXYlzBfXDrg= >>   |
  // ----------- >>
	  Rubic [][] rubices =  board.GetRubices();
	  for(int i = 0 ;  i < 3;i++)
	  {
		  for(int j = 0 ; j<3;j++)
		  {
			  if(postions == 0)
			  {
				  if(rubices[i][j].getMark() == ' ')
				  {
					  return true;
				  }
				  return false;
			  }
			 
					  
			postions--;
		  }
	  }
	  
	  return false;
	  
  }
  // ----------- << method.annotations@AAAAAAFqX8As9hxl4EM= >>
  // ----------- >>
  public void CheckWin() {
  // ----------- << method.body@AAAAAAFqX8As9hxl4EM= >>
  // ----------- >>
	  
	 

	  
  }
  // ----------- << method.annotations@AAAAAAFqX8DLTBxxdcg= >>
  // ----------- >>
  public void AddMoveToBoard(int postions,char mark) {
  // ----------- << method.body@AAAAAAFqX8DLTBxxdcg= >>
  // ----------- >>
	  
	  for(int i = 0 ;  i < 3;i++)
	  {
		  for(int j = 0 ; j<3;j++)
		  {
			  if(postions == 0)
			  {
				  registersMove(i, j, mark);

			  }
			 
					  
			postions--;
		  }
	  }
	  
  }
  public Boolean GetCurrectPlayer()
  {
    return this.currectPlayer;
  }
  // ----------- << method.annotations@AAAAAAFqEXy+QBhCKio= >>
  // ----------- >>
  public void registersMove(int row,int col,char mark) {
  // ----------- << method.body@AAAAAAFqEXy+QBhCKio= >>
  // ----------- >>
      this.board.GetRubices()[row][col].setMark(mark);
  }
  
  
  // ----------- << method.annotations@AAAAAAFqEYHjVxiQ3rk= >>
  // ----------- >>
  public void SwapPlayers() {
  // ----------- << method.body@AAAAAAFqEYHjVxiQ3rk= >>
  // ----------- >>
      this.currectPlayer = !this.currectPlayer;
  }
// ----------- << class.extras@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>

public void RestartGame() {
	// TODO Auto-generated method stub
	Rubic [][] rubices =  board.GetRubices();
	for(int i = 0 ; i<3;i++)
    {
      for(int j =0; j<3;j++)
      {
       
    	  rubices[i][j].setMark(' ');
        
      }
      
    }
	this.currectPlayer = true;
	
}
  // ----------- << method.annotations@AAAAAAFqX8HF6hx4wg4= >>
  // ----------- >>
 
  // ----------- << method.annotations@AAAAAAFqX8LzjhyoV7g= >>
  // ----------- >>
  public void ShowMessage() {
  // ----------- << method.body@AAAAAAFqX8LzjhyoV7g= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFp/Kvq2XBejTo= >>
// ----------- >>
}