/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package RootPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>
public class Board {
  // ----------- << attribute.annotations@AAAAAAFqEbOtPr4u4qs= >>
  // ----------- >>
  private void status;

  public void getStatus() {
    return status;
  }

  public void setStatus(void status) {
    this.status = status;
  }

  // ----------- << method.annotations@AAAAAAFqEWxj9hczLcE= >>
  // ----------- >>
  public void getBoard() {
  // ----------- << method.body@AAAAAAFqEWxj9hczLcE= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqEXy+QBhCKio= >>
  // ----------- >>
  public void registersMove() {
  // ----------- << method.body@AAAAAAFqEXy+QBhCKio= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqEYHjVxiQ3rk= >>
  // ----------- >>
  public void SwapPlayers() {
  // ----------- << method.body@AAAAAAFqEYHjVxiQ3rk= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFqEN9ZYRVzA5E= >>
// ----------- >>
}