/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package RootPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqELABfKZmiwM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqELABfKZmiwM= >>
// ----------- >>
public class Rubric {
  // ----------- << attribute.annotations@AAAAAAFqEbQ3jr4yisc= >>
  // ----------- >>
  private void mark;

  // ----------- << attribute.annotations@AAAAAAFqEbRcub427z8= >>
  // ----------- >>
  private void IsAvilable;

  public void getMark() {
    return mark;
  }

  public void getIsAvilable() {
    return IsAvilable;
  }

  public void setMark(void mark) {
    this.mark = mark;
  }

  public void setIsAvilable(void IsAvilable) {
    this.IsAvilable = IsAvilable;
  }

  // ----------- << method.annotations@AAAAAAFqEXdQyxfwwcA= >>
  // ----------- >>
  public void IsAvailableRubric() {
  // ----------- << method.body@AAAAAAFqEXdQyxfwwcA= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqEX2rbxhcoic= >>
  // ----------- >>
  public void SetAvilable() {
  // ----------- << method.body@AAAAAAFqEX2rbxhcoic= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFqELABfKZmiwM= >>
// ----------- >>
}